### PR TITLE
style: Adjust layout on max-width 667px by tweaking `.main` & `.plot`

### PR DESCRIPTION
**Pull request by icyJoseph**
Attempts to account for #93 - though I am not sure I've understood the media queries correctly. Does this fix the use cases you've found?

### CODE REVIEW

**Comment by mithi** [comment]
@icyJoseph 

It isn't fixed on my end...

# Firefox (around 712 px)
 
Screen Shot 2020-07-03 at 8 20 33 PM


# Chrome (around 666 px)

Screen Shot 2020-07-03 at 8 25 44 PM

**Comment by mithi** [comment]
Additional screenshots

Screen Shot 2020-07-03 at 8 37 04 PM

**Comment by mithi** [comment]
Last one...
Screen Shot 2020-07-03 at 8 39 41 PM

**Comment by icyJoseph** [comment]
Perfect :D!  I was having trouble finding those breakpoints! I'll squash this bug now!

**Comment by icyJoseph** [comment]
image

What are your thoughts on this layout for the affected widths?

**Comment by mithi** [comment]
@icyJoseph  awesome! Merging!

**Pull request merged**
