### PR TITLE
Move: hexapod/plotter to templates/plotter

### LINKED ISSUE #138: Move plotter from `src/hexapod` to `src/templates`
Move this whole file to the `src/templates` directory. Update all dependents and dependencies. Make sure nothing is broken.
https://github.com/mithi/hexapod/blob/cdd2f1e89cf3b2a1bffb32c4769d2f6a917e8b35/src/hexapod/plotter.js

**Rationale** 
The hexapod subdirectory contains all the files to compute the orientations and points of the hexapod, 
it shouldn't be in charge of displaying the hexapod. Also we want to move a couple of steps forward to making the `hexapod` subdirectory it's own package / library which can be called by any application. 

https://github.com/mithi/hexapod/blob/cdd2f1e89cf3b2a1bffb32c4769d2f6a917e8b35/src/hexapod/plotter.js#L1-L100

### PR DESCRIPTION
**Pull request by 2Shar18**
Closes #138 
This is my first contribution and PR, hope I am doing it in a proper way.
After making the changes, I tried testing and running the project with `npm test` and `npm start` with complete success.

### CODE REVIEW

**Comment by mithi** [comment]
> Closes #138
> This is my first contribution and PR, hope I am doing it in a proper way.
> After making the changes, I tried testing and running the project with `npm test` and `npm start` with complete success.


Thanks for your pull request!

The function `getNewPlotParams` in `plotter.js` is used by the `HexapodPlot` component (See `./src/components/HexapodPlot.js`) which is currently being imported from `./hexapod/` directory.
This is a round about ways of importing.

Can you remove the reference of `plotter` in `./hexapod/index.js` `HexapodPlot.js` import `getNewPlotParams` directly ? Thanks

### Currently
`src/templates/plotter.js` ---> `src/hexapod/index.js` ----> `src/component/HexapodPlot.js`
### Ideally
`src/templates/plotter.js` -----------------------------------> `src/component/HexapodPlot.js`

Thanks!

**Comment by 2Shar18** [comment]
> > Closes #138
> > This is my first contribution and PR, hope I am doing it in a proper way.
> > After making the changes, I tried testing and running the project with `npm test` and `npm start` with complete success.
> 
> Thanks for your pull request!
> 
> The function `getNewPlotParams` in `plotter.js` is used by the `HexapodPlot` component (See `./src/components/HexapodPlot.js`) which is currently being imported from `./hexapod/` directory.
> This is a round about ways of importing.
> 
> Can you remove the reference of `plotter` in `./hexapod/index.js` `HexapodPlot.js` import `getNewPlotParams` directly ? Thanks
> 
> ### Currently
> `src/templates/plotter.js` ---> `src/hexapod/index.js` ----> `src/component/HexapodPlot.js`
> 
> ### Ideally
> `src/templates/plotter.js` -----------------------------------> `src/component/HexapodPlot.js`
> 
> Thanks!

Thank you for pointing and very neatly explaining the thing I left out and giving me a chance to re-correct it. I have made the necessary changes and squashed the commits in to a single commit. Kindly have a look at it.

**Comment by mithi** [comment]
@2Shar18 Thanks! Merged! 😄

**Comment by 2Shar18** [comment]
@mithi Thank you for giving me the chance. And btw I love the project idea and would try to help and contribute in other issues too. 😀

**Comment by mithi** [comment]
> @mithi Thank you for giving me the chance. And btw I love the project idea and would try to help and contribute in other issues too. 😀

Btw, next time do not commit your `package.lock` because I'm using yarn :D

**Comment by 2Shar18** [comment]
> > @mithi Thank you for giving me the chance. And btw I love the project idea and would try to help and contribute in other issues too. 😀
> 
> Btw, next time do NOT commit your `package.lock` because I'm using yarn :D 

Oh, sorry for that. Will remember that and try to run with yarn itself.

**Comment by mithi** [comment]
> Oh, sorry for that. Will remember that and try to run with yarn itself.

I'm glad you like this project and thank you so much for your PR 😃

**Pull request merged**
